/*
 * Copyright (c) 2015. Qubole Inc
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.qubole.quark.jdbc.schema;

import com.fasterxml.jackson.annotation.JsonCreator;

import java.util.Map;

/**
 * An instance is generated by parsing JSON. The required properties are:
 * - name
 * - default
 */
public class DataSourceSchema extends com.qubole.quark.planner.DataSourceSchema {
  @JsonCreator
  public DataSourceSchema(Map<String, Object> properties) {
    super(properties);
  }
}
